/**
 * Crawl-control routes are generated by Next.js at runtime from
 * `src/app/sitemap.ts` and `src/app/robots.ts`.
 *
 * Content mutations used to write a second, stale sitemap and robots file into
 * `public/`. Keeping this compatibility function prevents existing admin/API
 * callers from failing while ensuring those mutations do not recreate drift.
 */
export function regenerateSitemapAndRobots() {
  console.info('Sitemap and robots are generated by Next.js runtime routes.');
}
